### ISSUE TITLE
gnureadline fails to build on yosemite with gcc-5.1

### ISSUE THREAD

**Issue by armando-fandango** [ludwigschwardt/python-gnureadline#44]
Python version is 2.7.10

This is the error I get:

checking whether make sets $(MAKE)... yes
  checking for gcc... /opt/local/apps/gcc/5.1.0/bin/gcc
  checking whether the C compiler works... no
  configure: error: in `/private/var/folders/q6/82ch7xnx3bsbm2ww5dddlj2r0000gn/T/pip-build-Eg8js8/gnureadline/rl/readline-lib':
  configure: error: C compiler cannot create executables
  See`config.log' for more details

**Comment by ludwigschwardt** [comment]
Yes, this is unfortunate.

The GNU gcc does not do fat / universal binaries from what I can tell. It also has this problem that the following flags work:

```
gcc -arch i386 ...
gcc -arch x86_64 ...
gcc -arch x86_64 -arch i386 ...
```
but the one actually in use in the build script doesn't:
```
gcc -arch i386 -arch x86_64 ...
```
Read more about it [here](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=60821).

The problem is that gcc picks the last flag, so the simplest solution (swapping the two flags) results in an incompatible 32-bit binary. I therefore still need to come up with a better solution.

**Comment by ludwigschwardt** [comment]
Tested successfully with Homebrew GCC 6.3.0_1 on OS 10.11.6, both with brew Python 2.7.13 and 3.6.0.
