### ISSUE TITLE
Geting the crash respond, Abort trap: 6, when a try the pyvisa

### ISSUE THREAD

**Issue by jorgla** [ludwigschwardt/python-gnureadline#53]
Hi Everyone,'
I try to run in the python shell some commands by using pyvisa. So I do the following as they show at https://pyvisa.readthedocs.io/en/master/. But when I write the line: rm = visa.ResourceManager() and press enter it crash and I get the Abort trap: 6 respond. Do anyone knows what can be wrong? My Python source is 3.6.3 and I uning the macOS Mojave.

**Comment by ludwigschwardt** [comment]
Are you sure this is due to readline? Try uninstalling gnureadline and see if the problem goes away.

**Comment by jorgla** [comment]
Hi Ludwig, thanks for the suggestion but it didn't help. I also have the same problem if I try to start a visa shell like python3 -m visa shell, and also crashes with the code Abort trap 6. So I start to wonder if it something wrong with the pyvisa it self.

**Comment by ludwigschwardt** [comment]
After the latest 8.0.0 release, I've checked this on macOS Mojave by installing Python 3.6.3 via pyenv:
```Bash
brew install pyenv
pyenv install 3.6.3
pyenv local 3.6.3
pip install pyvisa pyvisa-py gnureadline
cd ~/.pyenv/versions/3.6.3/lib/python3.6/site-packages
python
```
I got pyvisa-1.9.1 and pyvisa-py-0.3.1. I then checked that I could replace the built-in readline with `gnureadline` and performed the actions in the PyVISA docs:
```
>>> import readline
>>> import gnureadline
>>> gnureadline.parse_and_bind is readline.parse_and_bind
True
>>> import visa
>>> rm = visa.ResourceManager()
>>> rm.list_resources()
()
```
Since I don't see the issue, I'm closing this. Feel free to re-open if still needed, Jörgen!
